### PR TITLE
workaround defectdojo expecting a non-empty scanstarttime for their e…

### LINKED ISSUE #456: DefectDojo crashes if the engagement time is 0
We can set the scanstarttime to 0 in case of tests or when running individual components so let's work around this bug by checking for the value and setting it to now() if it's 0

### PR DESCRIPTION
**Pull request by northdpole**
…ngagments
fix #456

### CODE REVIEW

File: components/consumers/defectdojo/main.go [hunk 1]
```diff
@@ -27,6 +30,14 @@ var (
 	issueTemplate          string
 )
 
+func getEngagementTime(engagementTime *timestamppb.Timestamp, scanID string) string {
+	if time.Time.IsZero(engagementTime.AsTime()) {
```
Comment (andream16) [inline components/consumers/defectdojo/main.go:34]: Should this be done on `engagementTime` directly?

`engagementTime.AsTime().IsZero()`
